In [ ]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [ ]:
dataset = load_iris()
df = pd.DataFrame(data=np.c_[dataset.data,dataset.target],columns=np.append(dataset.feature_names,["target"]))
df
X = dataset.data
Y = dataset.target

In [ ]:
#Splitting

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 41)

In [ ]:
#Prediction

clf = GaussianNB()
clf.fit(X_train,Y_train)
Y_label = clf.predict(X_test)
print(Y_label) 
print(Y_test)

[1 2 2 1 2 1 2 1 2 2 2 0 0 1 0 1 0 1 0 0 1 2 0 0 1 1 1 1 0 1]
[2 2 2 1 2 1 2 1 2 2 2 0 0 1 0 2 0 1 0 0 1 2 0 0 1 1 1 1 0 1]


In [ ]:
#Performace Evaluation of the Classifier
from sklearn import metrics
print(metrics.classification_report(Y_test,Y_label))
conf_mat = metrics.confusion_matrix(Y_test,Y_label)
print("Confusion Matrix:\n",conf_mat)

print(len(conf_mat))
curr_class=0
for curr_class in range(len(conf_mat)):
  print("Metrics for class ",curr_class)
  TP,TN,FP,FN = 0,0,0,0
  for i in range(len(conf_mat)):
    for j in range(len(conf_mat[0])):
      if i==j and i==curr_class and j==curr_class:
        TP+=conf_mat[i][j]
      elif i!=curr_class and j!=curr_class:
        TN+=conf_mat[i][j]
      elif i==curr_class and j!=curr_class:
        FP+=conf_mat[i][j]
      elif j==curr_class and i!=curr_class:
        FN+=conf_mat[i][j]
  print("TP:",TP,"TN:",TN,"FP:",FP,"FN:",FN)
  TPR = TP/(TP+FN)
  FPR = FP/(FP+TN)
  FNR = 1-TPR
  TNR = 1-FPR
  print("TPR:",TPR,"\nFPR:",FPR,"\nFNR:",FNR,"\nTNR",TNR,"\n\n")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.85      1.00      0.92        11
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.95      0.93      0.94        30
weighted avg       0.94      0.93      0.93        30

Confusion Matrix:
 [[ 9  0  0]
 [ 0 11  0]
 [ 0  2  8]]
3
Metrics for class  0
TP: 9 TN: 21 FP: 0 FN: 0
TPR: 1.0 
FPR: 0.0 
FNR: 0.0 
TNR 1.0 


Metrics for class  1
TP: 11 TN: 17 FP: 0 FN: 2
TPR: 0.8461538461538461 
FPR: 0.0 
FNR: 0.15384615384615385 
TNR 1.0 


Metrics for class  2
TP: 8 TN: 20 FP: 2 FN: 0
TPR: 1.0 
FPR: 0.09090909090909091 
FNR: 0.0 
TNR 0.9090909090909091 


