In [ ]:
import numpy as np

Q1: Questions on Basic NumPy Array 

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr = np.array([1,2,3,6,4,5])
print(arr[::-1])
print(np.flipud(arr))

[5 4 6 3 2 1]
[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two 
NumPy in-built methods

In [ ]:
arr1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
print(arr1)
print(arr1.flatten())
print(np.reshape(arr1,(len(arr1)*len(arr1[0]))))

[[1 2 3]
 [2 4 5]
 [1 2 3]]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays: 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


In [ ]:
arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([[1,2],[3,4]])
np.array_equal(arr2,arr3)

True

(d) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
freqInX = np.bincount(x).argmax()
indexOfFreqInX = np. where(x == freqInX)
print(freqInX," ",indexOfFreqInX)
freqInY = np.bincount(y).argmax()
indexOfFreqInY = np. where(y == freqInY)
print(freqInY," ",indexOfFreqInY)

1   (array([0, 5, 7, 8, 9]),)
1   (array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
i. Sum of all elements 
ii. Sum of all elements row-wise 
iii. Sum of all elements column-wise 


In [ ]:
gfg = np.array([[4,1,9],[12,3,1],[4,5,6]])
print(np.sum(gfg))
print(gfg.sum(axis=0))
print(gfg.sum(axis=1))

45
[20  9 16]
[14 16 15]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements 
ii. Eigen values of matrix 
iii. Eigen vectors of matrix 
iv. Inverse of matrix 
v. Determinant of matrix 


In [ ]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print(np.trace(n_array))
print(np.linalg.eigvals(n_array))
print(np.linalg.eig(n_array))
print(np.linalg.inv(n_array))
# print(n_array.ndim)
print(np.linalg.det(n_array))

176
[98.16835147 28.097044   49.73460452]
(array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy: 
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]] 
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]


In [ ]:
p = [[1,2],[2,3]]
q = [[4,5],[6,7]]
print(np.matmul(p,q))
print(np.cov(p,q))
p = [[1,2],[2,3],[4,5]]
q = [[4,5,1],[6,7,2]]
print(np.matmul(p,q))
# print(np.cov(p,q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
find inner, outer and cartesian product?

In [ ]:
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
print(np.inner(x,y))
print(np.outer(x,y))
# print(np.cross(x,y))
# result = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
# print(result)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


Q2: Based on NumPy Mathematics and Statistics 

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value 
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
row. 
iii. Mean, Median and Standard Deviation of flattened array, of each column, and 
each row 

In [ ]:
array = np.array([[1,-2,3],[-4,5,-6]])
for row in array:
  for ele in row:
    print(abs(ele))
print(np.percentile(array.flatten(),25))
print(np.percentile(array,25,axis=0))
print(np.percentile(array,25,axis=1))
print(np.mean(array.flatten()))
print(np.mean(array,axis=0))
print(np.mean(array,axis=1))
print(np.median(array.flatten()))
print(np.median(array,axis=0))
print(np.median(array,axis=1))
print(np.std(array.flatten()))
print(np.std(array,axis=0))
print(np.std(array,axis=1))

1
2
3
4
5
6
-3.5
[-2.75 -0.25 -3.75]
[-0.5 -5. ]
-0.5
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]
-0.5
[-1.5  1.5 -1.5]
[ 1. -4.]
3.8622100754188224
[2.5 3.5 4.5]
[2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
and truncated value, rounded values


In [ ]:
a = np.array([-1.8,-1.6,-0.5,-0.5,1.6,1.8,3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.around(a))

[-2. -2. -1. -1.  1.  1.  3.]
[-1. -1. -0. -0.  2.  2.  3.]
[-1. -1. -0. -0.  1.  1.  3.]
[-2. -2. -0. -0.  2.  2.  3.]


**Q3: Based on Searching and Sorting**

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
i. Sorted array 
ii. Indices of sorted array 
iii. 4 smallest elements 
iv. 5 largest elements

In [ ]:
array22 = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array22))
indices = np.argsort(array22)
print(indices)
array23 = np.sort(array22)
k=4
print(k, "smallest elements of the array")
print(array23[:k])
k=5
print(k, "largest elements of the array")
print(array23[-k:])


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
4 smallest elements of the array
[10 16 16 52]
5 largest elements of the array
[ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
i. Integer elements only 
ii. Float elements only 


In [ ]:
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
print("Integer elements ->")
into=array[array==array.astype(int)]
print(into)
print("")
print("Float elements ->")
intf=array[array!=array.astype(int)]
print(intf)

Integer elements ->
[1. 2. 3. 2.]

Float elements ->
[1.2 2.2]


Q4: 
(a) Write a function named img_to_array(path) that reads an image from a specified path and 
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
images) 
(b) Load the saved file into jupyter notebook?

In [4]:
import numpy as np
from PIL import Image

def img_to_array_RGB(path):
  img = Image.open(path)
  numpydata = np.array(img)
  np.savetxt("a.txt",numpydata.reshape((3,-1)), fmt="%s")

def img_to_array_GS(path):
  img = Image.open(path)
  numpydata = np.array(img)
  np.savetxt("b.txt",numpydata.reshape((3,-1)), fmt="%s")

a = input("Enter the path of the RGB image")
b = input("Enter the path of the GrayScale image")
img_to_array_RGB(a)
img_to_array_GS(b)
print(np.loadtxt('a.txt'))
print(np.loadtxt('b.txt'))

Enter the path of the RGB image/content/RGB.jpg
Enter the path of the GrayScale image/content/GRAY.jpg
[[  3.   0.  69. ...  32. 246. 235.]
 [ 47. 255. 247. ...   4. 197.  26.]
 [  1. 204.  33. ...   0.   0.   2.]]
[[ 89.  89.  89. ...  96.  96.  96.]
 [118. 118. 118. ... 135. 135. 135.]
 [149. 149. 149. ... 102. 102. 102.]]
