In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Q1. K-Fold Cross Validation for Multiple Linear Regression (Least Square Error Fit) 
Download the dataset regarding USA House Price Prediction from the following link: 
https://drive.google.com/file/d/1O_NwpJT-8xGfU_-3llUl2sgPu0xllOrX/view?usp=sharing
Load the dataset and Implement 5- fold cross validation for multiple linear regression 
(using least square error fit). 
Steps: 
a) Divide the dataset into input features (all columns except price) and output variable 
(price) 
b) Scale the values of input features. 
c) Divide input and output features into five folds. 
d) Run five iterations, in each iteration consider one-fold as test set and remaining 
four sets as training set. Find the beta (𝛽) matrix, predicted values, and R2_score 
for each iteration using least square error fit. 
e) Use the best value of (𝛽) matrix (for which R2_score is maximum), to train the 
regressor for 70% of data and test the performance for remaining 30% data.


In [2]:
data = pd.read_csv("/content/USA_Housing.csv")
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188   
1       79248.64245             6.002900                   6.730821   
2       61287.06718             5.865890                   8.512727   
3       63345.24005             7.188236                   5.586729   
4       59982.19723             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09      23086.80050  1.059034e+06  
1                          3.09      40173.07217  1.505891e+06  
2                          5.13      36882.15940  1.058988e+06  
3                          3.26      34310.24283  1.260617e+06  
4                          4.23      26354.10947  6.309435e+05

In [3]:
#a
X = data.iloc[:,0:5]
Y = data.iloc[:,5]
Y = np.array(Y)
Y = Y.reshape(5000,1)
print(X)
print(Y)

      Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          79545.45857             5.682861                   7.009188   
1          79248.64245             6.002900                   6.730821   
2          61287.06718             5.865890                   8.512727   
3          63345.24005             7.188236                   5.586729   
4          59982.19723             5.040555                   7.839388   
...                ...                  ...                        ...   
4995       60567.94414             7.830362                   6.137356   
4996       78491.27543             6.999135                   6.576763   
4997       63390.68689             7.250591                   4.805081   
4998       68001.33124             5.534388                   7.130144   
4999       65510.58180             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population  
0                             4.09      23086.80050  
1  

In [4]:
#b
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled= np.insert(X_scaled, 0, values=1, axis=1)
print(X_scaled)

[[ 1.          1.02865969 -0.29692705  0.02127433  0.08806222 -1.31759867]
 [ 1.          1.00080775  0.02590164 -0.25550611 -0.72230146  0.40399945]
 [ 1.         -0.68462915 -0.11230283  1.5162435   0.93084045  0.07240989]
 ...
 [ 1.         -0.48723454  1.28447022 -2.17026949 -1.50025059 -0.29193658]
 [ 1.         -0.05459152 -0.44669439  0.14154061  1.18205319  0.65111608]
 [ 1.         -0.28831272  0.01521477 -0.19434166  0.07185495  1.04162464]]


In [5]:
#c
from sklearn.model_selection import KFold
cv = KFold(n_splits=5)

In [6]:
# d
for train_index,test_index in cv.split(X_scaled):
  X_train,X_test,Y_train,Y_test = X_scaled[train_index],X_scaled[test_index],Y[train_index],Y[test_index]
  # Beta = inv(X'X)X'Y
  A = X_train.T.dot(X_train)
  B = np.linalg.inv(A)
  C = B.dot(X_train.T)
  Beta = C.dot(Y_train)
  print ('Beta matrix:')
  print(Beta)
  print ('Predicted values:')
  predicted=X_test.dot(Beta)
  print (predicted[:5])
  error=Y_test-predicted
  square_error=np.power(error,2)
  sum_square_error=np.sum(square_error)
  y_mean=np.mean(Y_test)
  total_variance=np.sum((Y_test-y_mean)**2)
  print ("R-square value is ")
  print (1-sum_square_error/total_variance)

Beta matrix:
[[1231872.07704612]
 [ 229923.70318635]
 [ 164052.98579011]
 [ 120923.57426579]
 [   3533.77470973]
 [ 151855.58542488]]
Predicted values:
[[1222472.59789716]
 [1494131.15197358]
 [1253670.80242078]
 [1120389.19877662]
 [ 844315.19005474]]
R-square value is 
0.9175899480765107
Beta matrix:
[[1232586.40453402]
 [ 228365.32287054]
 [ 165201.14881927]
 [ 122539.46855211]
 [   1697.03433458]
 [ 150055.81710562]]
Predicted values:
[[ 950080.82206093]
 [ 711724.26608798]
 [1770455.57819769]
 [ 764563.88271977]
 [1572061.16316271]]
R-square value is 
0.920301549640113
Beta matrix:
[[1231448.09063371]
 [ 230730.20810582]
 [ 163554.55706976]
 [ 121669.08713233]
 [   2620.25215054]
 [ 150923.12489298]]
Predicted values:
[[1231513.14886101]
 [1321188.78204718]
 [ 725691.26810135]
 [ 932558.61953863]
 [1049638.8423876 ]]
R-square value is 
0.9152429915320014
Beta matrix:
[[1.23144707e+06]
 [2.29921558e+05]
 [1.64523054e+05]
 [1.19737507e+05]
 [1.12425659e+03]
 [1.51317802e+05]]
Predic

Q2. Concept of Validation set for Multiple Linear Regression (Gradient Descent 
Optimization) 
Consider the same dataset of Q1, rather than dividing the dataset into five folds, divide the 
dataset into training set (56%), validation set (14%), and test set (30%). 
Consider four different values of learning rate i.e. {0.001,0.01,0.1,1}. Compute the values of 
regression coefficients for each value of learning rate after 1000 iterations. 
For each set of regression coefficients, compute R2_score for validation and test set and find 
the best value of regression coefficients. 

In [10]:
#a
from sklearn.model_selection import train_test_split
x_temp,x_test,y_temp,y_test=train_test_split(X_scaled,Y,test_size=0.3,random_state=42)
x_train,x_validation,y_train,y_validation=train_test_split(x_temp,y_temp,test_size=0.2,random_state=42)

In [11]:
def gradient_descent(lrate): 
  beta=np.zeros(6) #initialising parametrs as 0, features are from 0 to 4 but as there is one constant beta naught in the multi variable regression, so number of gradients will be 6
  number_of_iterations=100
  n=x_train.shape[0]
  learning_rate=lrate
  for i in range(number_of_iterations):
    betatemp = np.zeroes(6)
    x0_gradient=0
    x1_gradient=0
    x2_gradient=0
    x3_gradient=0
    x4_gradient=0
    x5_gradient=0
    for j in range(len(x_train)):
      a=x_train[j,1]
      b=x_train[j,2]
      c=x_train[j,3]
      d=x_train[j,4]
      e=x_train[j,5]
      f=y_train[j]
      # this is the summation step
      x0_gradient=(beta[0]+beta[1]*a+beta[2]*b+beta[3]*c+beta[4]*d+beta[5]*e-f) 
      x1_gradient=((beta[0]+beta[1]*a+beta[2]*b+beta[3]*c+beta[4]*d+beta[5]*e-f)*a)
      x2_gradient=((beta[0]+beta[1]*a+beta[2]*b+beta[3]*c+beta[4]*d+beta[5]*e-f)*b)
      x3_gradient=((beta[0]+beta[1]*a+beta[2]*b+beta[3]*c+beta[4]*d+beta[5]*e-f)*c)
      x4_gradient=((beta[0]+beta[1]*a+beta[2]*b+beta[3]*c+beta[4]*d+beta[5]*e-f)*d)
      x5_gradient=((beta[0]+beta[1]*a+beta[2]*b+beta[3]*c+beta[4]*d+beta[5]*e-f)*e)
      #here beta values are getting updated
      beta[0]=beta[0]-lrate/n*x0_gradient
      beta[1]=beta[1]-lrate/n*x1_gradient
      beta[2]=beta[2]-lrate/n*x2_gradient
      beta[3]=beta[3]-lrate/n*x3_gradient
      beta[4]=beta[4]-lrate/n*x4_gradient
      beta[5]=beta[5]-lrate/n*x5_gradient
  print(beta)
  print("validation prediction")
  Validationresult = x_validation.dot(beta)
  Validationresult = Validationresult.reshape(-1,1)
  error = y_validation - Validationresult
  print(Validationresult[:5])
  square_error=np.power(error,2)
  sum_square_error=np.sum(square_error)
  y_mean=np.mean(Y_test)
  total_variance=np.sum((Y_test-y_mean)**2)
  print ("R-square value is ")
  print (1-sum_square_error/total_variance)
  print("Test prediction")
  Testresult = x_test.dot(beta)
  Testresult = Testresult.reshape(-1,1)
  error = y_test - Testresult
  print(Testresult[:5])
  square_error=np.power(error,2)
  sum_square_error=np.sum(square_error)
  y_mean=np.mean(Y_test)
  total_variance=np.sum((Y_test-y_mean)**2)
  print ("R-square value is ")
  print (1-sum_square_error/total_variance)

In [12]:
gradient_descent(0.001)

[614605.35242126 614605.35242126 226213.53035996 168110.11983764
 119427.56707278   3068.11617577]
validation prediction
[[ -94189.71721459]
 [ 739008.09492007]
 [ 679348.03452977]
 [ 179622.28072818]
 [2151999.33064124]]
R-square value is 
-2.3862281832088765
Test prediction
[[307139.27800567]
 [ 73642.10115589]
 [635237.14837833]
 [904009.18884391]
 [ 60343.21177234]]
R-square value is 
-6.31361092019829


In [13]:
gradient_descent(0.01)

[ 656734.51442872  656734.51442872  228240.02227399  110992.44868971
 -160967.40132457 -272093.82417291]
validation prediction
[[-231890.28641147]
 [ 752040.44889319]
 [1449950.13243632]
 [-122981.5094082 ]
 [2430956.07221149]]
R-square value is 
-2.9359157101209954
Test prediction
[[ 309751.05910388]
 [  67196.6157453 ]
 [1344335.38603891]
 [1156337.30022928]
 [  82844.33152457]]
R-square value is 
-8.1868412894087


In [14]:
gradient_descent(0.1)

[-6.17308901e+07 -6.17308901e+07  1.83721590e+07  4.46374809e+07
  2.93539731e+08 -3.12917167e+08]
validation prediction
[[ 6.02098390e+08]
 [-3.89643191e+08]
 [ 4.82834308e+08]
 [-1.46382791e+08]
 [ 6.57471042e+08]]
R-square value is 
-1142569.0060370567
Test prediction
[[-4.43728606e+08]
 [-4.14314834e+08]
 [-3.21098994e+08]
 [ 4.19743145e+08]
 [-9.69836958e+08]]
R-square value is 
-2719486.219837834


In [15]:
gradient_descent(1)

[-5.28602461e+38 -5.28602461e+38  6.88123726e+39  4.31106610e+39
 -5.82790894e+39  2.80307167e+39]
validation prediction
[[-9.95396879e+39]
 [ 1.86354137e+40]
 [ 3.22326198e+39]
 [-4.18756882e+39]
 [-2.94613005e+39]]
R-square value is 
-4.787416175689091e+68
Test prediction
[[ 1.02975168e+40]
 [ 1.21958032e+40]
 [ 1.06748593e+40]
 [ 7.55877105e+38]
 [-9.48811695e+39]]
R-square value is 
-1.0524705853045625e+69


Pre-processing and Multiple Linear Regression 
Download the dataset regarding Car Price Prediction from the following link: 
https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data
1. Load the dataset with following column names ["symboling", "normalized_losses", 
"make", "fuel_type", "aspiration","num_doors", "body_style", "drive_wheels", 
"engine_location", "wheel_base", "length", "width", "height", "curb_weight", 
"engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke", 
"compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"] 
and replace all ? values with NaN 
2. Replace all NaN values with central tendency imputation. Drop the rows with NaN 
values in price column 
3. There are 10 columns in the dataset with non-numeric values. Convert these values to 
numeric values using following scheme: 
(i) For “num_doors” and “num_cylinders”: convert words (number names) to figures 
for e.g., two to 2 
(ii) For "body_style", "drive_wheels": use dummy encoding scheme 
(iii) For “make”, “aspiration”, “engine_location”,fuel_type: use label encoding 
scheme 
(iv) For fuel_system: replace values containing string pfi to 1 else all values to 0. 
(v) For engine_type: replace values containing string ohc to 1 else all values to 0. 
4. Divide the dataset into input features (all columns except price) and output variable 
(price). Scale all input features. 
5. Train a linear regressor on 70% of data (using inbuilt linear regression function of 
Python) and test its performance on remaining 30% of data. 
6. Reduce the dimensionality of the feature set using inbuilt PCA decomposition and then 
again train a linear regressor on 70% of reduced data (using inbuilt linear regression 
function of Python). Does it lead to any performance improvement on test set?

In [31]:
#1
cols = ["symboling", "normalized_losses", 
"make", "fuel_type", "aspiration","num_doors", "body_style", "drive_wheels", 
"engine_location", "wheel_base", "length", "width", "height", "curb_weight", 
"engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke", 
"compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"]
cars = pd.read_csv("imports-85.csv", names = cols)
df = pd.DataFrame()
df = cars
df.head()

symboling normalized_losses         make fuel_type aspiration num_doors  \
0          3                 ?  alfa-romero       gas        std       two   
1          3                 ?  alfa-romero       gas        std       two   
2          1                 ?  alfa-romero       gas        std       two   
3          2               164         audi       gas        std      four   
4          2               164         audi       gas        std      four   

    body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel_system  bore  stroke compression_ratio horsepower  peak_rpm city_mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

  highway_mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [32]:
#1
df = df.replace('?',np.NaN)
df.head()

symboling normalized_losses         make fuel_type aspiration num_doors  \
0          3               NaN  alfa-romero       gas        std       two   
1          3               NaN  alfa-romero       gas        std       two   
2          1               NaN  alfa-romero       gas        std       two   
3          2               164         audi       gas        std      four   
4          2               164         audi       gas        std      four   

    body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel_system  bore  stroke compression_ratio horsepower  peak_rpm city_mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

  highway_mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [33]:
#2
from sklearn.impute import SimpleImputer
df.dropna(subset=['price'],inplace=True)
df = df.reset_index(drop=True)
imputer = SimpleImputer(missing_values = np.nan,
                        strategy ='most_frequent')
imputer1=imputer.fit(df)
df=pd.DataFrame(imputer1.transform(df))
df.columns=cols 
print(df)

    symboling normalized_losses         make fuel_type aspiration num_doors  \
0           3               161  alfa-romero       gas        std       two   
1           3               161  alfa-romero       gas        std       two   
2           1               161  alfa-romero       gas        std       two   
3           2               164         audi       gas        std      four   
4           2               164         audi       gas        std      four   
..        ...               ...          ...       ...        ...       ...   
196        -1                95        volvo       gas        std      four   
197        -1                95        volvo       gas      turbo      four   
198        -1                95        volvo       gas        std      four   
199        -1                95        volvo    diesel      turbo      four   
200        -1                95        volvo       gas      turbo      four   

      body_style drive_wheels engine_location wheel

In [34]:
#3 (i)
dict1={"one":1,"two":2,"three":3,"four":4,"five":5,"six":6,"seven":7,"eight":8,"nine":9,"zero":0,"twelve":12}
df['num_doors']=df['num_doors'].map(dict1)
df['num_cylinders']=df['num_cylinders'].map(dict1)

In [35]:
#3 (ii)
dummy_encoding_body_style=pd.get_dummies(df['body_style'],prefix="body_style",drop_first=True)
df=pd.concat([df,dummy_encoding_body_style],axis=1)
df.drop(['body_style'],axis=1,inplace=True)
dummy_encoding_drive_wheels=pd.get_dummies(df['drive_wheels'],prefix="drive_wheels",drop_first=True)
df.drop(['drive_wheels'],axis=1,inplace=True)
df=pd.concat([df,dummy_encoding_drive_wheels],axis=1)
print(df)

    symboling normalized_losses         make fuel_type aspiration  num_doors  \
0           3               161  alfa-romero       gas        std          2   
1           3               161  alfa-romero       gas        std          2   
2           1               161  alfa-romero       gas        std          2   
3           2               164         audi       gas        std          4   
4           2               164         audi       gas        std          4   
..        ...               ...          ...       ...        ...        ...   
196        -1                95        volvo       gas        std          4   
197        -1                95        volvo       gas      turbo          4   
198        -1                95        volvo       gas        std          4   
199        -1                95        volvo    diesel      turbo          4   
200        -1                95        volvo       gas      turbo          4   

    engine_location wheel_base length w

In [36]:
#3 (iii)
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['make']=encoder.fit_transform(df['make'])
df['aspiration']=encoder.fit_transform(df['aspiration'])
df['engine_location']=encoder.fit_transform(df['engine_location'])
df['fuel_type']=encoder.fit_transform(df['fuel_type'])

In [37]:
#3 (iv)
cond=(df['fuel_system'].str.contains('pfi')==True)
df.loc[cond,'fuel_system']=1
cond2=(df['fuel_system']).str.contains('pfi')==False
df.loc[cond2,'fuel_system']=0

In [38]:
#3 (v)
cond3=(df['engine_type'].str.contains('ohc')==True)
cond4=((df['engine_type']).str.contains('ohc')==False)
df.loc[cond3,'engine_type']=1
df.loc[cond4,'engine_type']=0

In [39]:
df.head()

symboling normalized_losses  make  fuel_type  aspiration  num_doors  \
0         3               161     0          1           0          2   
1         3               161     0          1           0          2   
2         1               161     0          1           0          2   
3         2               164     1          1           0          4   
4         2               164     1          1           0          4   

   engine_location wheel_base length width  ... peak_rpm city_mpg highway_mpg  \
0                0       88.6  168.8  64.1  ...     5000       21          27   
1                0       88.6  168.8  64.1  ...     5000       21          27   
2                0       94.5  171.2  65.5  ...     5000       19          26   
3                0       99.8  176.6  66.2  ...     5500       24          30   
4                0       99.4  176.6  66.4  ...     5500       18          22   

   price body_style_hardtop body_style_hatchback body_style_sedan  \
0  13495                  0                    0                0   
1  16500                  0                    0                0   
2  16500                  0                    1                0   
3  13950                  0                    0                1   
4  17450                  0                    0                1   

  body_style_wagon drive_wheels_fwd drive_wheels_rwd  
0                0                0                1  
1                0                0                1  
2                0                0                1  
3                0                1                0  
4                0                0                0  

[5 rows x 30 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   symboling             201 non-null    object
 1   normalized_losses     201 non-null    object
 2   make                  201 non-null    int64 
 3   fuel_type             201 non-null    int64 
 4   aspiration            201 non-null    int64 
 5   num_doors             201 non-null    int64 
 6   engine_location       201 non-null    int64 
 7   wheel_base            201 non-null    object
 8   length                201 non-null    object
 9   width                 201 non-null    object
 10  height                201 non-null    object
 11  curb_weight           201 non-null    object
 12  engine_type           201 non-null    object
 13  num_cylinders         201 non-null    int64 
 14  engine_size           201 non-null    object
 15  fuel_system           201 non-null    ob

In [41]:
#4
x_data=df.loc[:,df.columns!='price']
y_data=df.loc[:,df.columns=='price']

In [42]:
for i in df.columns: #converting data type to number if possible
  #https://stackoverflow.com/questions/54426845/how-to-check-if-a-pandas-dataframe-contains-only-numeric-column-wise
  df[i]=pd.to_numeric(df[i], errors='ignore')
for i in x_data.columns:
  x_data[i]=pd.to_numeric(x_data[i],errors='ignore')
for i in y_data:
  y_data[i]=pd.to_numeric(y_data[i],errors='ignore')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [43]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
features_to_scale=x_data.select_dtypes(np.number).columns 
# print(df.columns)
x_scaled=scaler.fit_transform(x_data[features_to_scale]) #specifying the columns to normalise
x_Scaled=pd.DataFrame(x_scaled,columns=features_to_scale)
x_data=x_Scaled #assigning the scaled values to x_data
print(x_data)

     symboling  normalized_losses      make  fuel_type  aspiration  num_doors  \
0          1.0           0.502618  0.000000        1.0         0.0        0.0   
1          1.0           0.502618  0.000000        1.0         0.0        0.0   
2          0.6           0.502618  0.000000        1.0         0.0        0.0   
3          0.8           0.518325  0.047619        1.0         0.0        1.0   
4          0.8           0.518325  0.047619        1.0         0.0        1.0   
..         ...                ...       ...        ...         ...        ...   
196        0.2           0.157068  1.000000        1.0         0.0        1.0   
197        0.2           0.157068  1.000000        1.0         1.0        1.0   
198        0.2           0.157068  1.000000        1.0         0.0        1.0   
199        0.2           0.157068  1.000000        0.0         1.0        1.0   
200        0.2           0.157068  1.000000        1.0         1.0        1.0   

     engine_location  wheel

In [44]:
print(x_data)
print(y_data)

     symboling  normalized_losses      make  fuel_type  aspiration  num_doors  \
0          1.0           0.502618  0.000000        1.0         0.0        0.0   
1          1.0           0.502618  0.000000        1.0         0.0        0.0   
2          0.6           0.502618  0.000000        1.0         0.0        0.0   
3          0.8           0.518325  0.047619        1.0         0.0        1.0   
4          0.8           0.518325  0.047619        1.0         0.0        1.0   
..         ...                ...       ...        ...         ...        ...   
196        0.2           0.157068  1.000000        1.0         0.0        1.0   
197        0.2           0.157068  1.000000        1.0         1.0        1.0   
198        0.2           0.157068  1.000000        1.0         0.0        1.0   
199        0.2           0.157068  1.000000        0.0         1.0        1.0   
200        0.2           0.157068  1.000000        1.0         1.0        1.0   

     engine_location  wheel

In [45]:
#5
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.3,random_state=42)
lr=LinearRegression()
lr.fit(x_train,y_train)
print(lr.score(x_test,y_test))

0.8680078106543799


In [47]:
#6
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
pca=PCA(n_components=11)
x_pca=pca.fit_transform(x_data)
x_train_pca,x_test_pca,y_train_pca,y_test_pca=train_test_split(x_pca,y_data,test_size=0.3,random_state=42)
lr.fit(x_train_pca,y_train_pca)
print(lr.score(x_test_pca,y_test_pca))

0.7711450688666883
