In [8]:
import numpy as np

In [3]:
# Q1a
arr = np.array([1, 2, 3, 6, 4, 5])
rev=np.flip(arr)
print(rev)

[5 4 6 3 2 1]


In [2]:
# Q1b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
x=array1.flatten()
flat=x.flatten()
print(flat)


[1 2 3 2 4 5 1 2 3]


In [4]:
# Q1c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
if(arr1.all()>arr2.all()):
    print("1st")
    
elif(arr1.all()<arr2.all()):
    print("2nd")
else:
    print("Equal")


Equal


In [5]:
# Q1d
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
unique_rows, indices, occurrence_count = np.unique(x, axis=0, return_counts=True, return_index=True)
print(occurrence_count)
print(indices)

unique_rows, indices, occurrence_count = np.unique(y, axis=0, return_counts=True, return_index=True)
print(occurrence_count)
print(indices)

[5 2 1 1 1]
[0 1 2 3 4]
[3 2 3 2]
[0 3 4 5]


In [6]:
# Q1e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print(gfg.sum(axis=1))  #rowise
print(gfg.sum(axis=0))  #columnwise

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [8]:
# Q1f
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
from numpy import linalg as LA
w, v = LA.eig(((n_array)))
print(w) #values
print(v) #vector
print(LA.inv(n_array)) #inverse
print(LA.det(n_array)) #determinant


176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [9]:
# Q1g
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
p1 = [[1, 2], [2, 3], [4, 5]]
q1 = [[4, 5, 1], [6, 7, 2]]


x=np.matmul(p,q)
print(x)
print(np.cov(x))
x1=np.matmul(p1,q1)
print(np.cov(x1))
print(x1)




[[16 19]
 [26 31]]
[[ 4.5  7.5]
 [ 7.5 12.5]]
[[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [10]:
# Q1h

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print(np.inner(x,y))
print(np.outer(x,y))

cross_product = np.transpose([np.repeat(y,len(x))])
print(cross_product)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 1]
 [ 1]
 [ 5]
 [ 5]
 [ 0]
 [ 0]
 [ 5]
 [ 5]
 [10]
 [10]
 [ 3]
 [ 3]]


In [11]:
# Q2a
arr = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.absolute(arr))
print("arr : ", arr)
print("50th percentile of arr : ",np.percentile(arr, 50))
print("25th percentile of arr : ",np.percentile(arr, 25))
print("75th percentile of arr : ",np.percentile(arr, 75))

print("mean",np.mean(arr))
print("median",np.median(arr))
print("std dev",np.std(arr))


[[1 2 3]
 [4 5 6]]
arr :  [[ 1 -2  3]
 [-4  5 -6]]
50th percentile of arr :  -0.5
25th percentile of arr :  -3.5
75th percentile of arr :  2.5
mean -0.5
median -0.5
std dev 3.8622100754188224


In [36]:
# Q2b
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [41]:
# Q3a
array = np.array([10, 52, 62, 16, 16, 54, 453])
x=np.sort(array)
print(x)

for item in x:
    itemindex = np.where(array == item)
    print(itemindex)

print(x[:4])
print(x[len(x)-5:])

[ 10  16  16  52  54  62 453]
(array([0], dtype=int64),)
(array([3, 4], dtype=int64),)
(array([3, 4], dtype=int64),)
(array([1], dtype=int64),)
(array([5], dtype=int64),)
(array([2], dtype=int64),)
(array([6], dtype=int64),)
[10 16 16 52]
[ 16  52  54  62 453]


In [14]:
# Q3b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0,1])

for i in array:
    if(np.dtype(i)=='int'):
        print(i)
    elif(np.dtype(i)=='float64'):
        print(i)

1.0
1.2
2.2
2.0
3.0
2.0
1.0


In [4]:
# Q4
from PIL import Image
import numpy as np
import cv2
path="tower.jpg"
im = Image.open(path) # img size (42, 349, 4)
np_im = np.array(im)
print(np_im.shape)
with open('imgfile.txt', 'w') as outfile:
    for slice_2d in np_im:
         np.savetxt(outfile, slice_2d)
             
p=cv2.imread("tower.jpg")
cv2.imshow("image",p)

(1066, 640, 3)


: 